import comingSoon from './assets/coming-soon.svg';
import imgDosaTawa from './assets/images/dosa-tawa.jpg';
import imgIdliSteamer from './assets/images/idli-steamer.jpg';
import imgWetGrinder from './assets/images/wet-grinder.jpg';
import imgRiceBoiler from './assets/images/rice-boiler.jpg';
import imgWorkTable from './assets/images/work-table.jpg';
import imgGasRange from './assets/images/gas-range.jpg';
import imgVisiCooler from './assets/images/visi-cooler.jpg';
import imgBainMarie from './assets/images/bain-marie.jpg';
import imgExhaustHood from './assets/images/exhaust-hood.jpg';
import imgBakingOven from './assets/images/baking-oven.jpg';
import imgTandoorOven from './assets/images/tandoor-oven.jpg';

export const products = [
  {
    "id": 1,
    "name": "Commercial Dosa Tawa 3ft",
    "category": "Dosa & Tawa Equipment",
    "description": "Commercial heavy duty Dosa Tawa crafted for hotel and restaurant kitchens.",
    "keywords": [
      "commercial",
      "dosa",
      "tawa",
      "3ft",
      "equipment",
      "dosa pan",
      "dosa plate",
      "griddle",
      "flat top",
      "commercial dosa equipment",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgDosaTawa,
      "side": imgGasRange,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 2,
    "name": "Commercial Dosa Tawa 4ft",
    "category": "Dosa & Tawa Equipment",
    "description": "Large 4ft commercial Dosa Tawa for high-volume morning breakfast service.",
    "keywords": [
      "commercial",
      "dosa",
      "tawa",
      "4ft",
      "equipment",
      "dosa pan",
      "dosa plate",
      "griddle",
      "flat top",
      "commercial dosa equipment",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgGasRange,
      "side": imgDosaTawa,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 3,
    "name": "Commercial Dosa Tawa 5ft",
    "category": "Dosa & Tawa Equipment",
    "description": "Extra-large 5ft commercial Dosa Tawa for banquet and catering operations.",
    "keywords": [
      "commercial",
      "dosa",
      "tawa",
      "5ft",
      "equipment",
      "dosa pan",
      "dosa plate",
      "griddle",
      "flat top",
      "commercial dosa equipment",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgDosaTawa,
      "side": imgGasRange,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 4,
    "name": "Chapati Puffer Plate",
    "category": "Dosa & Tawa Equipment",
    "description": "Commercial Chapati puffer and roasting plate unit.",
    "keywords": [
      "chapati",
      "puffer",
      "plate",
      "dosa",
      "tawa",
      "equipment",
      "roaster",
      "flat top",
      "dosa pan",
      "kitchen equipment"
    ],
    "images": {
      "front": imgGasRange,
      "side": imgDosaTawa,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 5,
    "name": "Omelette Tawa",
    "category": "Dosa & Tawa Equipment",
    "description": "Dedicated commercial round cast iron tawa for fast egg preparations.",
    "keywords": [
      "omelette",
      "tawa",
      "dosa",
      "equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgDosaTawa,
      "side": imgGasRange,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 6,
    "name": "Fish Fry Tawa",
    "category": "Dosa & Tawa Equipment",
    "description": "Shallow fry commercial tawa designed for fish and meat pan frying.",
    "keywords": [
      "fish",
      "fry",
      "tawa",
      "dosa",
      "equipment",
      "deep fryer",
      "fryer",
      "fish fry",
      "shallow fry",
      "kitchen equipment"
    ],
    "images": {
      "front": imgGasRange,
      "side": imgDosaTawa,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 7,
    "name": "Parotta Master Tawa",
    "category": "Dosa & Tawa Equipment",
    "description": "Heavy gauge steel tawa designed specifically for South Indian Parotta making.",
    "keywords": [
      "parotta",
      "master",
      "tawa",
      "dosa",
      "equipment",
      "kothu",
      "kothu parotta",
      "flat top",
      "kitchen equipment"
    ],
    "images": {
      "front": imgDosaTawa,
      "side": imgGasRange,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 8,
    "name": "Appam Chatti Range",
    "category": "Dosa & Tawa Equipment",
    "description": "Customized multi-burner gas range built for holding traditional Appam pans.",
    "keywords": [
      "appam",
      "chatti",
      "range",
      "dosa",
      "tawa",
      "equipment",
      "stove",
      "commercial stove",
      "burner",
      "gas range",
      "tandoor",
      "charcoal tandoor",
      "gas tandoor",
      "shawarma",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgGasRange,
      "side": imgDosaTawa,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 9,
    "name": "Paniyaram Tawa (Commercial)",
    "category": "Dosa & Tawa Equipment",
    "description": "Commercial multi-cavity cast iron pan unit for Kuzhi Paniyaram.",
    "keywords": [
      "paniyaram",
      "tawa",
      "commercial",
      "dosa",
      "equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgDosaTawa,
      "side": imgGasRange,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 10,
    "name": "Kothu Parotta Station",
    "category": "Dosa & Tawa Equipment",
    "description": "Heavy reinforced steel flat top cooking station for chopping Kothu Parotta.",
    "keywords": [
      "kothu",
      "parotta",
      "station",
      "dosa",
      "tawa",
      "equipment",
      "kothu parotta",
      "flat top",
      "kitchen equipment"
    ],
    "images": {
      "front": imgGasRange,
      "side": imgDosaTawa,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 11,
    "name": "Idli Steamer 54 Plates",
    "category": "Idli & Steaming Equipment",
    "description": "Commercial stainless steel Idli steaming chamber with 54-plate capacity.",
    "keywords": [
      "idli",
      "steamer",
      "54",
      "plates",
      "steaming",
      "equipment",
      "idly",
      "idli equipment",
      "rice",
      "dhokla",
      "momo",
      "puttu",
      "idiyappam",
      "steam",
      "boiler",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgIdliSteamer,
      "side": imgRiceBoiler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 12,
    "name": "Idli Steamer 72 Plates",
    "category": "Idli & Steaming Equipment",
    "description": "High-capacity commercial Idli steamer for large restaurants and messes.",
    "keywords": [
      "idli",
      "steamer",
      "72",
      "plates",
      "steaming",
      "equipment",
      "idly",
      "idli equipment",
      "rice",
      "dhokla",
      "momo",
      "puttu",
      "idiyappam",
      "steam",
      "boiler",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgRiceBoiler,
      "side": imgIdliSteamer,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 13,
    "name": "Idli Steamer 108 Plates",
    "category": "Idli & Steaming Equipment",
    "description": "Industrial scale Idli steamer cabinet for institutional catering.",
    "keywords": [
      "idli",
      "steamer",
      "108",
      "plates",
      "steaming",
      "equipment",
      "idly",
      "idli equipment",
      "rice",
      "dhokla",
      "momo",
      "puttu",
      "idiyappam",
      "steam",
      "boiler",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgIdliSteamer,
      "side": imgRiceBoiler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 14,
    "name": "Gas Rice Steamer",
    "category": "Idli & Steaming Equipment",
    "description": "Heavy duty gas-operated steaming plant for bulk rice preparation.",
    "keywords": [
      "gas",
      "rice",
      "steamer",
      "idli",
      "steaming",
      "equipment",
      "idly",
      "idli equipment",
      "dhokla",
      "momo",
      "puttu",
      "idiyappam",
      "steam",
      "boiler",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgRiceBoiler,
      "side": imgIdliSteamer,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 15,
    "name": "Electric Rice Steamer",
    "category": "Idli & Steaming Equipment",
    "description": "Commercial electric steamer unit for uniform rice cooking.",
    "keywords": [
      "electric",
      "rice",
      "steamer",
      "idli",
      "steaming",
      "equipment",
      "idly",
      "idli equipment",
      "dhokla",
      "momo",
      "puttu",
      "idiyappam",
      "steam",
      "boiler",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgIdliSteamer,
      "side": imgRiceBoiler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 16,
    "name": "Momo Steamer 3 Tier",
    "category": "Idli & Steaming Equipment",
    "description": "Stainless steel multi-tier steamer unit for dim sums and momos.",
    "keywords": [
      "momo",
      "steamer",
      "3",
      "tier",
      "idli",
      "steaming",
      "equipment",
      "idly",
      "idli equipment",
      "rice",
      "dhokla",
      "puttu",
      "idiyappam",
      "steam",
      "boiler",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgRiceBoiler,
      "side": imgIdliSteamer,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 17,
    "name": "Puttu Maker Commercial",
    "category": "Idli & Steaming Equipment",
    "description": "Multi-pipe steam attachment for commercial Kerala Puttu preparation.",
    "keywords": [
      "puttu",
      "maker",
      "commercial",
      "idli",
      "steaming",
      "equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgIdliSteamer,
      "side": imgRiceBoiler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 18,
    "name": "Idiyappam Steamer",
    "category": "Idli & Steaming Equipment",
    "description": "Tray-based commercial steaming unit designed for string hoppers / Idiyappam.",
    "keywords": [
      "idiyappam",
      "steamer",
      "idli",
      "steaming",
      "equipment",
      "idly",
      "idli equipment",
      "rice",
      "dhokla",
      "momo",
      "puttu",
      "steam",
      "boiler",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgRiceBoiler,
      "side": imgIdliSteamer,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 19,
    "name": "Commercial Dhokla Steamer",
    "category": "Idli & Steaming Equipment",
    "description": "Heavy duty stainless steel tray steamer for bulk snack production.",
    "keywords": [
      "commercial",
      "dhokla",
      "steamer",
      "idli",
      "steaming",
      "equipment",
      "idly",
      "idli equipment",
      "rice",
      "momo",
      "puttu",
      "idiyappam",
      "steam",
      "boiler",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgIdliSteamer,
      "side": imgRiceBoiler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 20,
    "name": "Idli Box (Table Top)",
    "category": "Idli & Steaming Equipment",
    "description": "Compact table-top steamer box for small eateries and tiffin centers.",
    "keywords": [
      "idli",
      "box",
      "table",
      "top",
      "steaming",
      "equipment",
      "idly",
      "idli equipment",
      "steamer",
      "rice",
      "dhokla",
      "momo",
      "puttu",
      "idiyappam",
      "steam",
      "ss",
      "ss equipment",
      "stainless steel",
      "work table",
      "sink",
      "storage",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgRiceBoiler,
      "side": imgIdliSteamer,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 21,
    "name": "Tilting Wet Grinder 10L",
    "category": "Grinding & Pulverizing",
    "description": "Commercial granite stone wet grinder with easy tilting mechanism.",
    "keywords": [
      "tilting",
      "wet",
      "grinder",
      "10l",
      "grinding",
      "pulverizing",
      "wet grinder",
      "tilting grinder",
      "batter",
      "pulverizer",
      "peeler",
      "potato peeler",
      "coconut scraper",
      "mixer",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 22,
    "name": "Tilting Wet Grinder 20L",
    "category": "Grinding & Pulverizing",
    "description": "20 Liter commercial wet grinder for continuous batter grinding.",
    "keywords": [
      "tilting",
      "wet",
      "grinder",
      "20l",
      "grinding",
      "pulverizing",
      "wet grinder",
      "tilting grinder",
      "batter",
      "pulverizer",
      "peeler",
      "potato peeler",
      "coconut scraper",
      "mixer",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 23,
    "name": "Tilting Wet Grinder 40L",
    "category": "Grinding & Pulverizing",
    "description": "Heavy industrial 40 Liter granite wet grinder for high volume batter production.",
    "keywords": [
      "tilting",
      "wet",
      "grinder",
      "40l",
      "grinding",
      "pulverizing",
      "wet grinder",
      "tilting grinder",
      "batter",
      "pulverizer",
      "peeler",
      "potato peeler",
      "coconut scraper",
      "mixer",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 24,
    "name": "Conventional Wet Grinder 15L",
    "category": "Grinding & Pulverizing",
    "description": "Standard commercial upright stone wet grinder unit.",
    "keywords": [
      "conventional",
      "wet",
      "grinder",
      "15l",
      "grinding",
      "pulverizing",
      "wet grinder",
      "tilting grinder",
      "batter",
      "pulverizer",
      "peeler",
      "potato peeler",
      "coconut scraper",
      "mixer",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 25,
    "name": "Potato Peeler 10kg",
    "category": "Grinding & Pulverizing",
    "description": "Commercial abrasive drum potato and root vegetable peeling machine.",
    "keywords": [
      "potato",
      "peeler",
      "10kg",
      "grinding",
      "pulverizing",
      "grinder",
      "wet grinder",
      "tilting grinder",
      "batter",
      "pulverizer",
      "potato peeler",
      "coconut scraper",
      "mixer",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 26,
    "name": "Potato Peeler 20kg",
    "category": "Grinding & Pulverizing",
    "description": "Heavy-duty 20kg batch vegetable peeler for bulk preparation.",
    "keywords": [
      "potato",
      "peeler",
      "20kg",
      "grinding",
      "pulverizing",
      "grinder",
      "wet grinder",
      "tilting grinder",
      "batter",
      "pulverizer",
      "potato peeler",
      "coconut scraper",
      "mixer",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 27,
    "name": "Coconut Scraper Machine",
    "category": "Grinding & Pulverizing",
    "description": "Motorized dual-blade commercial coconut grater unit.",
    "keywords": [
      "coconut",
      "scraper",
      "machine",
      "grinding",
      "pulverizing",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 28,
    "name": "Masala Pulverizer",
    "category": "Grinding & Pulverizing",
    "description": "Commercial stainless steel dry spice pulverizer machine.",
    "keywords": [
      "masala",
      "pulverizer",
      "grinding",
      "pulverizing",
      "grinder",
      "wet grinder",
      "tilting grinder",
      "batter",
      "peeler",
      "potato peeler",
      "coconut scraper",
      "mixer",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 29,
    "name": "Commercial Mixer Grinder",
    "category": "Grinding & Pulverizing",
    "description": "Heavy-duty high RPM commercial kitchen mixer grinder.",
    "keywords": [
      "commercial",
      "mixer",
      "grinder",
      "grinding",
      "pulverizing",
      "wet grinder",
      "tilting grinder",
      "batter",
      "pulverizer",
      "peeler",
      "potato peeler",
      "coconut scraper",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 30,
    "name": "Gravy Machine / Gravy Master",
    "category": "Grinding & Pulverizing",
    "description": "Continuous wet grinding machine for onion, tomato, and gravy pastes.",
    "keywords": [
      "gravy",
      "machine",
      "master",
      "grinding",
      "pulverizing",
      "grinder",
      "wet grinder",
      "tilting grinder",
      "batter",
      "pulverizer",
      "peeler",
      "potato peeler",
      "coconut scraper",
      "mixer",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 31,
    "name": "SS Rice Boiler 50kg",
    "category": "Boiling & Cooking",
    "description": "Stainless steel double-jacketed steam rice boiling vessel.",
    "keywords": [
      "ss",
      "rice",
      "boiler",
      "50kg",
      "boiling",
      "cooking",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgRiceBoiler,
      "side": imgDosaTawa,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 32,
    "name": "SS Rice Boiler 100kg",
    "category": "Boiling & Cooking",
    "description": "Industrial volume steam rice boiler kettle for mass feeding.",
    "keywords": [
      "ss",
      "rice",
      "boiler",
      "100kg",
      "boiling",
      "cooking",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgDosaTawa,
      "side": imgRiceBoiler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 33,
    "name": "Sambar Boiler 100L",
    "category": "Boiling & Cooking",
    "description": "Steam jacketed cooking kettle for Sambar, Rasam, and curries.",
    "keywords": [
      "sambar",
      "boiler",
      "100l",
      "boiling",
      "cooking",
      "rice",
      "rice boiler",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgRiceBoiler,
      "side": imgDosaTawa,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 34,
    "name": "Sambar Boiler 200L",
    "category": "Boiling & Cooking",
    "description": "Large capacity tilting liquid boiling vessel.",
    "keywords": [
      "sambar",
      "boiler",
      "200l",
      "boiling",
      "cooking",
      "rice",
      "rice boiler",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgDosaTawa,
      "side": imgRiceBoiler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 35,
    "name": "Milk Boiler 50L",
    "category": "Boiling & Cooking",
    "description": "Water-jacketed commercial milk boiling vessel to prevent scorching.",
    "keywords": [
      "milk",
      "boiler",
      "50l",
      "boiling",
      "cooking",
      "rice",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgRiceBoiler,
      "side": imgDosaTawa,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 36,
    "name": "Tea / Coffee Boiler 20L",
    "category": "Boiling & Cooking",
    "description": "Commercial electric hot water and beverage dispensing boiler.",
    "keywords": [
      "tea",
      "coffee",
      "boiler",
      "20l",
      "boiling",
      "cooking",
      "rice",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgDosaTawa,
      "side": imgRiceBoiler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 37,
    "name": "Tilting Boiling Pan 100L",
    "category": "Boiling & Cooking",
    "description": "Easy-tilt cooking pan for gravies, stocks, and liquid foods.",
    "keywords": [
      "tilting",
      "boiling",
      "pan",
      "100l",
      "cooking",
      "kitchen equipment"
    ],
    "images": {
      "front": imgRiceBoiler,
      "side": imgDosaTawa,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 38,
    "name": "Gas Soup Boiler",
    "category": "Boiling & Cooking",
    "description": "Heavy duty stock pot stove and kettle unit for soups and broth.",
    "keywords": [
      "gas",
      "soup",
      "boiler",
      "boiling",
      "cooking",
      "rice",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgDosaTawa,
      "side": imgRiceBoiler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 39,
    "name": "Steam Generator Unit",
    "category": "Boiling & Cooking",
    "description": "Dedicated gas or electric steam boiler for kitchen equipment line.",
    "keywords": [
      "steam",
      "generator",
      "unit",
      "boiling",
      "cooking",
      "idli",
      "idly",
      "idli equipment",
      "steamer",
      "steaming",
      "rice",
      "dhokla",
      "momo",
      "puttu",
      "idiyappam",
      "boiler",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "biryani",
      "vessel",
      "dum",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgRiceBoiler,
      "side": imgDosaTawa,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 40,
    "name": "Biryani Dum Vessel",
    "category": "Boiling & Cooking",
    "description": "Traditional thick-bottom stainless steel vessel for dum cooking.",
    "keywords": [
      "biryani",
      "dum",
      "vessel",
      "boiling",
      "cooking",
      "boiler",
      "rice",
      "rice boiler",
      "sambar",
      "sambar boiler",
      "soup",
      "milk",
      "tea",
      "coffee",
      "cooking equipment",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgDosaTawa,
      "side": imgRiceBoiler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 41,
    "name": "SS Work Table (4ft)",
    "category": "Work Tables & Storage",
    "description": "Stainless steel food preparation table with under-shelf.",
    "keywords": [
      "ss",
      "work",
      "table",
      "4ft",
      "tables",
      "storage",
      "ss equipment",
      "stainless steel",
      "work table",
      "sink",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 42,
    "name": "SS Work Table (6ft)",
    "category": "Work Tables & Storage",
    "description": "Heavy gauge stainless steel kitchen work table.",
    "keywords": [
      "ss",
      "work",
      "table",
      "6ft",
      "tables",
      "storage",
      "ss equipment",
      "stainless steel",
      "work table",
      "sink",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 43,
    "name": "SS Work Table with Sink",
    "category": "Work Tables & Storage",
    "description": "Integrated preparation table with built-in washing sink.",
    "keywords": [
      "ss",
      "work",
      "table",
      "with",
      "sink",
      "tables",
      "storage",
      "ss equipment",
      "stainless steel",
      "work table",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 44,
    "name": "SS Chopping Table",
    "category": "Work Tables & Storage",
    "description": "Reinforced steel table fitted with commercial poly cutting board.",
    "keywords": [
      "ss",
      "chopping",
      "table",
      "work",
      "tables",
      "storage",
      "ss equipment",
      "stainless steel",
      "work table",
      "sink",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 45,
    "name": "Dough Kneading Table",
    "category": "Work Tables & Storage",
    "description": "Heavy sturdy work table designed for dough rolling and bakery prep.",
    "keywords": [
      "dough",
      "kneading",
      "table",
      "work",
      "tables",
      "storage",
      "ss",
      "ss equipment",
      "stainless steel",
      "work table",
      "sink",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 46,
    "name": "SS Storage Rack 4 Tier",
    "category": "Work Tables & Storage",
    "description": "4-tier stainless steel open storage shelving rack.",
    "keywords": [
      "ss",
      "storage",
      "rack",
      "4",
      "tier",
      "work",
      "tables",
      "ss equipment",
      "stainless steel",
      "work table",
      "table",
      "sink",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 47,
    "name": "Pot Rack",
    "category": "Work Tables & Storage",
    "description": "Heavy duty tubular steel rack for drying large pots and pans.",
    "keywords": [
      "pot",
      "rack",
      "work",
      "tables",
      "storage",
      "ss",
      "ss equipment",
      "stainless steel",
      "work table",
      "table",
      "sink",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 48,
    "name": "Wall Mounted SS Shelf",
    "category": "Work Tables & Storage",
    "description": "Space-saving wall-mounted stainless steel shelf.",
    "keywords": [
      "wall",
      "mounted",
      "ss",
      "shelf",
      "work",
      "tables",
      "storage",
      "ss equipment",
      "stainless steel",
      "work table",
      "table",
      "sink",
      "rack",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 49,
    "name": "Onion / Potato Bin",
    "category": "Work Tables & Storage",
    "description": "Perforated stainless steel ventilated storage bin for vegetables.",
    "keywords": [
      "onion",
      "potato",
      "bin",
      "work",
      "tables",
      "storage",
      "ss",
      "ss equipment",
      "stainless steel",
      "work table",
      "table",
      "sink",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 50,
    "name": "Plate Rack",
    "category": "Work Tables & Storage",
    "description": "Stainless steel dish draining and storage rack.",
    "keywords": [
      "plate",
      "rack",
      "work",
      "tables",
      "storage",
      "ss",
      "ss equipment",
      "stainless steel",
      "work table",
      "table",
      "sink",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 51,
    "name": "2 Burner Indian Gas Range",
    "category": "Commercial Ranges",
    "description": "Heavy duty 2-burner commercial gas stove.",
    "keywords": [
      "2",
      "burner",
      "indian",
      "gas",
      "range",
      "commercial",
      "ranges",
      "stove",
      "commercial stove",
      "gas range",
      "tandoor",
      "charcoal tandoor",
      "gas tandoor",
      "shawarma",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgGasRange,
      "side": imgTandoorOven,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 52,
    "name": "3 Burner Indian Gas Range",
    "category": "Commercial Ranges",
    "description": "Commercial 3-burner gas cooking range.",
    "keywords": [
      "3",
      "burner",
      "indian",
      "gas",
      "range",
      "commercial",
      "ranges",
      "stove",
      "commercial stove",
      "gas range",
      "tandoor",
      "charcoal tandoor",
      "gas tandoor",
      "shawarma",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgTandoorOven,
      "side": imgGasRange,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 53,
    "name": "4 Burner Continental Range",
    "category": "Commercial Ranges",
    "description": "4-burner range with heavy cast iron pan supports.",
    "keywords": [
      "4",
      "burner",
      "continental",
      "range",
      "commercial",
      "ranges",
      "stove",
      "commercial stove",
      "gas range",
      "tandoor",
      "charcoal tandoor",
      "gas tandoor",
      "shawarma",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgGasRange,
      "side": imgTandoorOven,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 54,
    "name": "2 Burner Chinese Range",
    "category": "Commercial Ranges",
    "description": "High pressure wok burner range with water wash channel.",
    "keywords": [
      "2",
      "burner",
      "chinese",
      "range",
      "commercial",
      "ranges",
      "stove",
      "commercial stove",
      "gas range",
      "tandoor",
      "charcoal tandoor",
      "gas tandoor",
      "shawarma",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgTandoorOven,
      "side": imgGasRange,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 55,
    "name": "Stock Pot Stove (Single)",
    "category": "Commercial Ranges",
    "description": "Low-height heavy duty burner stove for stock pots.",
    "keywords": [
      "stock",
      "pot",
      "stove",
      "single",
      "commercial",
      "ranges",
      "commercial stove",
      "burner",
      "gas range",
      "tandoor",
      "charcoal tandoor",
      "gas tandoor",
      "shawarma",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgGasRange,
      "side": imgTandoorOven,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 56,
    "name": "Bulk Cooking Gas Range",
    "category": "Commercial Ranges",
    "description": "Extra heavy cast iron gas range for large vessel cooking.",
    "keywords": [
      "bulk",
      "cooking",
      "gas",
      "range",
      "commercial",
      "ranges",
      "stove",
      "commercial stove",
      "burner",
      "gas range",
      "tandoor",
      "charcoal tandoor",
      "gas tandoor",
      "shawarma",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgTandoorOven,
      "side": imgGasRange,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 57,
    "name": "SS Charcoal Tandoor",
    "category": "Commercial Ranges",
    "description": "Stainless steel jacketed traditional clay tandoor oven.",
    "keywords": [
      "ss",
      "charcoal",
      "tandoor",
      "commercial",
      "ranges",
      "stove",
      "commercial stove",
      "burner",
      "gas range",
      "charcoal tandoor",
      "gas tandoor",
      "shawarma",
      "cooking equipment",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgGasRange,
      "side": imgTandoorOven,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 58,
    "name": "Gas Tandoor Oven",
    "category": "Commercial Ranges",
    "description": "Gas-fired commercial clay tandoor for naans and kebabs.",
    "keywords": [
      "gas",
      "tandoor",
      "oven",
      "commercial",
      "ranges",
      "stove",
      "commercial stove",
      "burner",
      "gas range",
      "charcoal tandoor",
      "gas tandoor",
      "shawarma",
      "cooking equipment",
      "baking oven",
      "deck oven",
      "rotary oven",
      "dough mixer",
      "pizza oven",
      "conveyor pizza oven",
      "waffle",
      "blender",
      "kitchen equipment"
    ],
    "images": {
      "front": imgTandoorOven,
      "side": imgGasRange,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 59,
    "name": "Shawarma Machine 2 Burner",
    "category": "Commercial Ranges",
    "description": "Vertical gas burner rotisserie for Shawarma.",
    "keywords": [
      "shawarma",
      "machine",
      "2",
      "burner",
      "commercial",
      "ranges",
      "stove",
      "commercial stove",
      "gas range",
      "tandoor",
      "charcoal tandoor",
      "gas tandoor",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgGasRange,
      "side": imgTandoorOven,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 60,
    "name": "Commercial Salamander",
    "category": "Commercial Ranges",
    "description": "Overhead radiant heater for grilling, melting, and browning.",
    "keywords": [
      "commercial",
      "salamander",
      "ranges",
      "stove",
      "commercial stove",
      "burner",
      "gas range",
      "tandoor",
      "charcoal tandoor",
      "gas tandoor",
      "shawarma",
      "cooking equipment",
      "kitchen equipment"
    ],
    "images": {
      "front": imgTandoorOven,
      "side": imgGasRange,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 61,
    "name": "Visi Cooler 300L",
    "category": "Refrigeration",
    "description": "Glass door display chiller for beverages and dairy.",
    "keywords": [
      "visi",
      "cooler",
      "300l",
      "refrigeration",
      "chiller",
      "visi cooler",
      "freezer",
      "deep freezer",
      "chest freezer",
      "fridge",
      "refrigerator",
      "kitchen equipment"
    ],
    "images": {
      "front": imgVisiCooler,
      "side": imgVisiCooler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 62,
    "name": "Visi Cooler 500L",
    "category": "Refrigeration",
    "description": "Double door commercial glass display refrigerator.",
    "keywords": [
      "visi",
      "cooler",
      "500l",
      "refrigeration",
      "chiller",
      "visi cooler",
      "freezer",
      "deep freezer",
      "chest freezer",
      "fridge",
      "refrigerator",
      "kitchen equipment"
    ],
    "images": {
      "front": imgVisiCooler,
      "side": imgVisiCooler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 63,
    "name": "Under Counter Chiller 2 Door",
    "category": "Refrigeration",
    "description": "Under-counter refrigerated worktable unit.",
    "keywords": [
      "under",
      "counter",
      "chiller",
      "2",
      "door",
      "refrigeration",
      "cooler",
      "visi cooler",
      "freezer",
      "deep freezer",
      "chest freezer",
      "fridge",
      "refrigerator",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment"
    ],
    "images": {
      "front": imgVisiCooler,
      "side": imgVisiCooler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 64,
    "name": "Under Counter Chiller 3 Door",
    "category": "Refrigeration",
    "description": "3-door stainless steel under-counter chiller.",
    "keywords": [
      "under",
      "counter",
      "chiller",
      "3",
      "door",
      "refrigeration",
      "cooler",
      "visi cooler",
      "freezer",
      "deep freezer",
      "chest freezer",
      "fridge",
      "refrigerator",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment"
    ],
    "images": {
      "front": imgVisiCooler,
      "side": imgVisiCooler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 65,
    "name": "Chest Freezer 300L",
    "category": "Refrigeration",
    "description": "Hard-top commercial deep freezer.",
    "keywords": [
      "chest",
      "freezer",
      "300l",
      "refrigeration",
      "cooler",
      "chiller",
      "visi cooler",
      "deep freezer",
      "chest freezer",
      "fridge",
      "refrigerator",
      "kitchen equipment"
    ],
    "images": {
      "front": imgVisiCooler,
      "side": imgVisiCooler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 66,
    "name": "Chest Freezer 500L",
    "category": "Refrigeration",
    "description": "Large storage commercial chest freezer.",
    "keywords": [
      "chest",
      "freezer",
      "500l",
      "refrigeration",
      "cooler",
      "chiller",
      "visi cooler",
      "deep freezer",
      "chest freezer",
      "fridge",
      "refrigerator",
      "kitchen equipment"
    ],
    "images": {
      "front": imgVisiCooler,
      "side": imgVisiCooler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 67,
    "name": "Vertical Freezer 2 Door",
    "category": "Refrigeration",
    "description": "Upright stainless steel commercial freezer.",
    "keywords": [
      "vertical",
      "freezer",
      "2",
      "door",
      "refrigeration",
      "cooler",
      "chiller",
      "visi cooler",
      "deep freezer",
      "chest freezer",
      "fridge",
      "refrigerator",
      "kitchen equipment"
    ],
    "images": {
      "front": imgVisiCooler,
      "side": imgVisiCooler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 68,
    "name": "Vertical Chiller 4 Door",
    "category": "Refrigeration",
    "description": "Reach-in 4 door commercial storage chiller.",
    "keywords": [
      "vertical",
      "chiller",
      "4",
      "door",
      "refrigeration",
      "cooler",
      "visi cooler",
      "freezer",
      "deep freezer",
      "chest freezer",
      "fridge",
      "refrigerator",
      "kitchen equipment"
    ],
    "images": {
      "front": imgVisiCooler,
      "side": imgVisiCooler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 69,
    "name": "Salad Prep Counter",
    "category": "Refrigeration",
    "description": "Refrigerated preparation counter with ingredient pan cutouts.",
    "keywords": [
      "salad",
      "prep",
      "counter",
      "refrigeration",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment"
    ],
    "images": {
      "front": imgVisiCooler,
      "side": imgVisiCooler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 70,
    "name": "Water Cooler 150L",
    "category": "Refrigeration",
    "description": "Commercial stainless steel chilled water dispenser.",
    "keywords": [
      "water",
      "cooler",
      "150l",
      "refrigeration",
      "chiller",
      "visi cooler",
      "freezer",
      "deep freezer",
      "chest freezer",
      "fridge",
      "refrigerator",
      "kitchen equipment"
    ],
    "images": {
      "front": imgVisiCooler,
      "side": imgVisiCooler,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 71,
    "name": "Hot Bain Marie 4 Pan",
    "category": "Display & Service",
    "description": "Electric warm food display counter with GN pan inserts.",
    "keywords": [
      "hot",
      "bain",
      "marie",
      "4",
      "pan",
      "display",
      "service",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBainMarie,
      "side": imgBainMarie,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 72,
    "name": "Hot Bain Marie 6 Pan",
    "category": "Display & Service",
    "description": "6-pan hot food holding service counter.",
    "keywords": [
      "hot",
      "bain",
      "marie",
      "6",
      "pan",
      "display",
      "service",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBainMarie,
      "side": imgBainMarie,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 73,
    "name": "Sweet Display Counter (Curved Glass)",
    "category": "Display & Service",
    "description": "Refrigerated curved glass showcase for sweet shops.",
    "keywords": [
      "sweet",
      "display",
      "counter",
      "curved",
      "glass",
      "service",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgBainMarie,
      "side": imgBainMarie,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 74,
    "name": "Bakery Display Counter",
    "category": "Display & Service",
    "description": "Glass display cabinet for cakes and pastries.",
    "keywords": [
      "bakery",
      "display",
      "counter",
      "service",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBainMarie,
      "side": imgBainMarie,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 75,
    "name": "Chaat Counter Unit",
    "category": "Display & Service",
    "description": "Customized stainless steel counter for street food preparation.",
    "keywords": [
      "chaat",
      "counter",
      "unit",
      "display",
      "service",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBainMarie,
      "side": imgBainMarie,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 76,
    "name": "Juice Counter",
    "category": "Display & Service",
    "description": "Stainless steel preparation counter with ice trough for juice bars.",
    "keywords": [
      "juice",
      "counter",
      "display",
      "service",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBainMarie,
      "side": imgBainMarie,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 77,
    "name": "Ice Cream Display Freezer",
    "category": "Display & Service",
    "description": "Glass canopy scooping freezer for ice cream parlors.",
    "keywords": [
      "ice",
      "cream",
      "display",
      "freezer",
      "service",
      "cooler",
      "chiller",
      "visi cooler",
      "deep freezer",
      "chest freezer",
      "fridge",
      "refrigerator",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBainMarie,
      "side": imgBainMarie,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 78,
    "name": "Popcorn Machine",
    "category": "Display & Service",
    "description": "Commercial heated popcorn popping unit.",
    "keywords": [
      "popcorn",
      "machine",
      "display",
      "service",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBainMarie,
      "side": imgBainMarie,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 79,
    "name": "Hot Dog Roller",
    "category": "Display & Service",
    "description": "Commercial rotating roller grill for sausages.",
    "keywords": [
      "hot",
      "dog",
      "roller",
      "display",
      "service",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBainMarie,
      "side": imgBainMarie,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 80,
    "name": "Food Warming Showcase",
    "category": "Display & Service",
    "description": "Heated glass cabinet display for hot bakery items.",
    "keywords": [
      "food",
      "warming",
      "showcase",
      "display",
      "service",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBainMarie,
      "side": imgBainMarie,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 81,
    "name": "Single Sink Unit",
    "category": "Wash & Exhaust",
    "description": "Commercial deep bowl stainless steel washing sink.",
    "keywords": [
      "single",
      "sink",
      "unit",
      "wash",
      "exhaust",
      "ss",
      "ss equipment",
      "stainless steel",
      "work table",
      "table",
      "storage",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgExhaustHood,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 82,
    "name": "Double Sink Unit",
    "category": "Wash & Exhaust",
    "description": "Two-compartment pot and dish washing sink.",
    "keywords": [
      "double",
      "sink",
      "unit",
      "wash",
      "exhaust",
      "ss",
      "ss equipment",
      "stainless steel",
      "work table",
      "table",
      "storage",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgExhaustHood,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 83,
    "name": "Pre-Wash Sink with Spray",
    "category": "Wash & Exhaust",
    "description": "Pre-rinse sink fitted with overhead spray tap.",
    "keywords": [
      "pre-wash",
      "sink",
      "with",
      "spray",
      "wash",
      "exhaust",
      "ss",
      "ss equipment",
      "stainless steel",
      "work table",
      "table",
      "storage",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgExhaustHood,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 84,
    "name": "Commercial Dishwasher (Hood Type)",
    "category": "Wash & Exhaust",
    "description": "High-capacity pass-through hood dishwasher.",
    "keywords": [
      "commercial",
      "dishwasher",
      "hood",
      "type",
      "wash",
      "exhaust",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgExhaustHood,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 85,
    "name": "Under Counter Dishwasher",
    "category": "Wash & Exhaust",
    "description": "Compact under-counter glass and dish washer.",
    "keywords": [
      "under",
      "counter",
      "dishwasher",
      "wash",
      "exhaust",
      "bain marie",
      "hot bain marie",
      "sweet display",
      "bakery display",
      "chaat counter",
      "warmer",
      "display counter",
      "food warmer",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgExhaustHood,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 86,
    "name": "SS Exhaust Hood (Island)",
    "category": "Wash & Exhaust",
    "description": "Stainless steel island exhaust canopy with baffle filters.",
    "keywords": [
      "ss",
      "exhaust",
      "hood",
      "island",
      "wash",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgExhaustHood,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 87,
    "name": "SS Exhaust Hood (Wall Mounted)",
    "category": "Wash & Exhaust",
    "description": "Wall-mounted commercial kitchen ventilation hood.",
    "keywords": [
      "ss",
      "exhaust",
      "hood",
      "wall",
      "mounted",
      "wash",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgExhaustHood,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 88,
    "name": "Fresh Air Makeup Unit",
    "category": "Wash & Exhaust",
    "description": "Commercial kitchen air supply and ventilation unit.",
    "keywords": [
      "fresh",
      "air",
      "makeup",
      "unit",
      "wash",
      "exhaust",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgExhaustHood,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 89,
    "name": "Grease Trap",
    "category": "Wash & Exhaust",
    "description": "Stainless steel under-sink grease interceptor unit.",
    "keywords": [
      "grease",
      "trap",
      "wash",
      "exhaust",
      "kitchen equipment",
      "ss equipment",
      "stainless steel"
    ],
    "images": {
      "front": imgExhaustHood,
      "side": imgWorkTable,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 90,
    "name": "Garbage Bin Trolley",
    "category": "Wash & Exhaust",
    "description": "Mobile stainless steel frame waste container.",
    "keywords": [
      "garbage",
      "bin",
      "trolley",
      "wash",
      "exhaust",
      "ss",
      "ss equipment",
      "stainless steel",
      "work table",
      "table",
      "sink",
      "storage",
      "rack",
      "shelf",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWorkTable,
      "side": imgExhaustHood,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 91,
    "name": "Single Deck Baking Oven",
    "category": "Bakery & Sweets",
    "description": "Commercial gas/electric tray deck baking oven.",
    "keywords": [
      "single",
      "deck",
      "baking",
      "oven",
      "bakery",
      "sweets",
      "baking oven",
      "deck oven",
      "rotary oven",
      "dough mixer",
      "pizza oven",
      "conveyor pizza oven",
      "waffle",
      "blender",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBakingOven,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 92,
    "name": "Double Deck Baking Oven",
    "category": "Bakery & Sweets",
    "description": "Two-deck commercial baking oven for bakeries.",
    "keywords": [
      "double",
      "deck",
      "baking",
      "oven",
      "bakery",
      "sweets",
      "baking oven",
      "deck oven",
      "rotary oven",
      "dough mixer",
      "pizza oven",
      "conveyor pizza oven",
      "waffle",
      "blender",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgBakingOven,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 93,
    "name": "Rotary Rack Oven",
    "category": "Bakery & Sweets",
    "description": "Industrial rotating rack baking oven.",
    "keywords": [
      "rotary",
      "rack",
      "oven",
      "bakery",
      "sweets",
      "ss",
      "ss equipment",
      "stainless steel",
      "work table",
      "table",
      "sink",
      "storage",
      "shelf",
      "baking oven",
      "deck oven",
      "rotary oven",
      "dough mixer",
      "pizza oven",
      "conveyor pizza oven",
      "waffle",
      "blender",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBakingOven,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 94,
    "name": "Spiral Dough Mixer 20kg",
    "category": "Bakery & Sweets",
    "description": "Heavy duty spiral dough kneader for bread and pizza.",
    "keywords": [
      "spiral",
      "dough",
      "mixer",
      "20kg",
      "bakery",
      "sweets",
      "grinder",
      "wet grinder",
      "tilting grinder",
      "batter",
      "pulverizer",
      "peeler",
      "potato peeler",
      "coconut scraper",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgBakingOven,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 95,
    "name": "Planetary Mixer 20L",
    "category": "Bakery & Sweets",
    "description": "Multi-purpose commercial mixer for batter, cream, and dough.",
    "keywords": [
      "planetary",
      "mixer",
      "20l",
      "bakery",
      "sweets",
      "grinder",
      "wet grinder",
      "tilting grinder",
      "batter",
      "pulverizer",
      "peeler",
      "potato peeler",
      "coconut scraper",
      "mixer grinder",
      "gravy machine",
      "gravy master",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBakingOven,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 96,
    "name": "Dough Sheeter",
    "category": "Bakery & Sweets",
    "description": "Floor-standing commercial pastry dough laminating sheeter.",
    "keywords": [
      "dough",
      "sheeter",
      "bakery",
      "sweets",
      "oven",
      "baking oven",
      "deck oven",
      "rotary oven",
      "dough mixer",
      "pizza oven",
      "conveyor pizza oven",
      "waffle",
      "blender",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgBakingOven,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 97,
    "name": "Bread Slicer",
    "category": "Bakery & Sweets",
    "description": "Electric commercial loaf slicing machine.",
    "keywords": [
      "bread",
      "slicer",
      "bakery",
      "sweets",
      "oven",
      "baking oven",
      "deck oven",
      "rotary oven",
      "dough mixer",
      "pizza oven",
      "conveyor pizza oven",
      "waffle",
      "blender",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBakingOven,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 98,
    "name": "Conveyor Pizza Oven",
    "category": "Bakery & Sweets",
    "description": "Continuous conveyor baking oven for pizza.",
    "keywords": [
      "conveyor",
      "pizza",
      "oven",
      "bakery",
      "sweets",
      "baking oven",
      "deck oven",
      "rotary oven",
      "dough mixer",
      "pizza oven",
      "conveyor pizza oven",
      "waffle",
      "blender",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgBakingOven,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 99,
    "name": "Waffle Baker",
    "category": "Bakery & Sweets",
    "description": "Commercial cast iron waffle iron.",
    "keywords": [
      "waffle",
      "baker",
      "bakery",
      "sweets",
      "oven",
      "baking oven",
      "deck oven",
      "rotary oven",
      "dough mixer",
      "pizza oven",
      "conveyor pizza oven",
      "blender",
      "kitchen equipment"
    ],
    "images": {
      "front": imgBakingOven,
      "side": imgWetGrinder,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  },
  {
    "id": 100,
    "name": "Commercial Blender",
    "category": "Bakery & Sweets",
    "description": "High speed commercial bar and kitchen blender.",
    "keywords": [
      "commercial",
      "blender",
      "bakery",
      "sweets",
      "oven",
      "baking oven",
      "deck oven",
      "rotary oven",
      "dough mixer",
      "pizza oven",
      "conveyor pizza oven",
      "waffle",
      "kitchen equipment"
    ],
    "images": {
      "front": imgWetGrinder,
      "side": imgBakingOven,
      "rear": comingSoon,
      "top": comingSoon,
      "detail": comingSoon
    },
    "price": null,
    "specs": []
  }
];

export const categories = [
  "Dosa & Tawa Equipment",
  "Idli & Steaming Equipment",
  "Grinding & Pulverizing",
  "Boiling & Cooking",
  "Work Tables & Storage",
  "Commercial Ranges",
  "Refrigeration",
  "Display & Service",
  "Wash & Exhaust",
  "Bakery & Sweets"
];
